//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notes.AuthService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthService.AuthControllerSoap")]
    public interface AuthControllerSoap {
        
        // CODEGEN: Generating message contract since element name password from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        Notes.AuthService.LoginResponse Login(Notes.AuthService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<Notes.AuthService.LoginResponse> LoginAsync(Notes.AuthService.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Signup", ReplyAction="*")]
        Notes.AuthService.SignupResponse Signup(Notes.AuthService.SignupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Signup", ReplyAction="*")]
        System.Threading.Tasks.Task<Notes.AuthService.SignupResponse> SignupAsync(Notes.AuthService.SignupRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public Notes.AuthService.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(Notes.AuthService.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string role;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string password, string email, string role) {
            this.password = password;
            this.email = email;
            this.role = role;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public Notes.AuthService.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(Notes.AuthService.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Notes.AuthService.ArrayOfString LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(Notes.AuthService.ArrayOfString LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Signup", Namespace="http://tempuri.org/", Order=0)]
        public Notes.AuthService.SignupRequestBody Body;
        
        public SignupRequest() {
        }
        
        public SignupRequest(Notes.AuthService.SignupRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignupRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string full_name;
        
        public SignupRequestBody() {
        }
        
        public SignupRequestBody(string email, string password, string full_name) {
            this.email = email;
            this.password = password;
            this.full_name = full_name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignupResponse", Namespace="http://tempuri.org/", Order=0)]
        public Notes.AuthService.SignupResponseBody Body;
        
        public SignupResponse() {
        }
        
        public SignupResponse(Notes.AuthService.SignupResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignupResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Notes.AuthService.ArrayOfString SignupResult;
        
        public SignupResponseBody() {
        }
        
        public SignupResponseBody(Notes.AuthService.ArrayOfString SignupResult) {
            this.SignupResult = SignupResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthControllerSoapChannel : Notes.AuthService.AuthControllerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthControllerSoapClient : System.ServiceModel.ClientBase<Notes.AuthService.AuthControllerSoap>, Notes.AuthService.AuthControllerSoap {
        
        public AuthControllerSoapClient() {
        }
        
        public AuthControllerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthControllerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthControllerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthControllerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Notes.AuthService.LoginResponse Notes.AuthService.AuthControllerSoap.Login(Notes.AuthService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public Notes.AuthService.ArrayOfString Login(string password, string email, string role) {
            Notes.AuthService.LoginRequest inValue = new Notes.AuthService.LoginRequest();
            inValue.Body = new Notes.AuthService.LoginRequestBody();
            inValue.Body.password = password;
            inValue.Body.email = email;
            inValue.Body.role = role;
            Notes.AuthService.LoginResponse retVal = ((Notes.AuthService.AuthControllerSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Notes.AuthService.LoginResponse> Notes.AuthService.AuthControllerSoap.LoginAsync(Notes.AuthService.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Notes.AuthService.LoginResponse> LoginAsync(string password, string email, string role) {
            Notes.AuthService.LoginRequest inValue = new Notes.AuthService.LoginRequest();
            inValue.Body = new Notes.AuthService.LoginRequestBody();
            inValue.Body.password = password;
            inValue.Body.email = email;
            inValue.Body.role = role;
            return ((Notes.AuthService.AuthControllerSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Notes.AuthService.SignupResponse Notes.AuthService.AuthControllerSoap.Signup(Notes.AuthService.SignupRequest request) {
            return base.Channel.Signup(request);
        }
        
        public Notes.AuthService.ArrayOfString Signup(string email, string password, string full_name) {
            Notes.AuthService.SignupRequest inValue = new Notes.AuthService.SignupRequest();
            inValue.Body = new Notes.AuthService.SignupRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            inValue.Body.full_name = full_name;
            Notes.AuthService.SignupResponse retVal = ((Notes.AuthService.AuthControllerSoap)(this)).Signup(inValue);
            return retVal.Body.SignupResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Notes.AuthService.SignupResponse> Notes.AuthService.AuthControllerSoap.SignupAsync(Notes.AuthService.SignupRequest request) {
            return base.Channel.SignupAsync(request);
        }
        
        public System.Threading.Tasks.Task<Notes.AuthService.SignupResponse> SignupAsync(string email, string password, string full_name) {
            Notes.AuthService.SignupRequest inValue = new Notes.AuthService.SignupRequest();
            inValue.Body = new Notes.AuthService.SignupRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            inValue.Body.full_name = full_name;
            return ((Notes.AuthService.AuthControllerSoap)(this)).SignupAsync(inValue);
        }
    }
}
