//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notes.NoteService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NoteService.NoteControllerSoap")]
    public interface NoteControllerSoap {
        
        // CODEGEN: Generating message contract since element name title from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateNote", ReplyAction="*")]
        Notes.NoteService.CreateNoteResponse CreateNote(Notes.NoteService.CreateNoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateNote", ReplyAction="*")]
        System.Threading.Tasks.Task<Notes.NoteService.CreateNoteResponse> CreateNoteAsync(Notes.NoteService.CreateNoteRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteNote", ReplyAction="*")]
        Notes.NoteService.DeleteNoteResponse DeleteNote(Notes.NoteService.DeleteNoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteNote", ReplyAction="*")]
        System.Threading.Tasks.Task<Notes.NoteService.DeleteNoteResponse> DeleteNoteAsync(Notes.NoteService.DeleteNoteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateNoteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateNote", Namespace="http://tempuri.org/", Order=0)]
        public Notes.NoteService.CreateNoteRequestBody Body;
        
        public CreateNoteRequest() {
        }
        
        public CreateNoteRequest(Notes.NoteService.CreateNoteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateNoteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string body;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string user_id;
        
        public CreateNoteRequestBody() {
        }
        
        public CreateNoteRequestBody(string title, string body, string user_id) {
            this.title = title;
            this.body = body;
            this.user_id = user_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateNoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateNoteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Notes.NoteService.CreateNoteResponseBody Body;
        
        public CreateNoteResponse() {
        }
        
        public CreateNoteResponse(Notes.NoteService.CreateNoteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateNoteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Notes.NoteService.ArrayOfString CreateNoteResult;
        
        public CreateNoteResponseBody() {
        }
        
        public CreateNoteResponseBody(Notes.NoteService.ArrayOfString CreateNoteResult) {
            this.CreateNoteResult = CreateNoteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteNoteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteNote", Namespace="http://tempuri.org/", Order=0)]
        public Notes.NoteService.DeleteNoteRequestBody Body;
        
        public DeleteNoteRequest() {
        }
        
        public DeleteNoteRequest(Notes.NoteService.DeleteNoteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteNoteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public DeleteNoteRequestBody() {
        }
        
        public DeleteNoteRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteNoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteNoteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Notes.NoteService.DeleteNoteResponseBody Body;
        
        public DeleteNoteResponse() {
        }
        
        public DeleteNoteResponse(Notes.NoteService.DeleteNoteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteNoteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Notes.NoteService.ArrayOfString DeleteNoteResult;
        
        public DeleteNoteResponseBody() {
        }
        
        public DeleteNoteResponseBody(Notes.NoteService.ArrayOfString DeleteNoteResult) {
            this.DeleteNoteResult = DeleteNoteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NoteControllerSoapChannel : Notes.NoteService.NoteControllerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NoteControllerSoapClient : System.ServiceModel.ClientBase<Notes.NoteService.NoteControllerSoap>, Notes.NoteService.NoteControllerSoap {
        
        public NoteControllerSoapClient() {
        }
        
        public NoteControllerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NoteControllerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NoteControllerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NoteControllerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Notes.NoteService.CreateNoteResponse Notes.NoteService.NoteControllerSoap.CreateNote(Notes.NoteService.CreateNoteRequest request) {
            return base.Channel.CreateNote(request);
        }
        
        public Notes.NoteService.ArrayOfString CreateNote(string title, string body, string user_id) {
            Notes.NoteService.CreateNoteRequest inValue = new Notes.NoteService.CreateNoteRequest();
            inValue.Body = new Notes.NoteService.CreateNoteRequestBody();
            inValue.Body.title = title;
            inValue.Body.body = body;
            inValue.Body.user_id = user_id;
            Notes.NoteService.CreateNoteResponse retVal = ((Notes.NoteService.NoteControllerSoap)(this)).CreateNote(inValue);
            return retVal.Body.CreateNoteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Notes.NoteService.CreateNoteResponse> Notes.NoteService.NoteControllerSoap.CreateNoteAsync(Notes.NoteService.CreateNoteRequest request) {
            return base.Channel.CreateNoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Notes.NoteService.CreateNoteResponse> CreateNoteAsync(string title, string body, string user_id) {
            Notes.NoteService.CreateNoteRequest inValue = new Notes.NoteService.CreateNoteRequest();
            inValue.Body = new Notes.NoteService.CreateNoteRequestBody();
            inValue.Body.title = title;
            inValue.Body.body = body;
            inValue.Body.user_id = user_id;
            return ((Notes.NoteService.NoteControllerSoap)(this)).CreateNoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Notes.NoteService.DeleteNoteResponse Notes.NoteService.NoteControllerSoap.DeleteNote(Notes.NoteService.DeleteNoteRequest request) {
            return base.Channel.DeleteNote(request);
        }
        
        public Notes.NoteService.ArrayOfString DeleteNote(string id) {
            Notes.NoteService.DeleteNoteRequest inValue = new Notes.NoteService.DeleteNoteRequest();
            inValue.Body = new Notes.NoteService.DeleteNoteRequestBody();
            inValue.Body.id = id;
            Notes.NoteService.DeleteNoteResponse retVal = ((Notes.NoteService.NoteControllerSoap)(this)).DeleteNote(inValue);
            return retVal.Body.DeleteNoteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Notes.NoteService.DeleteNoteResponse> Notes.NoteService.NoteControllerSoap.DeleteNoteAsync(Notes.NoteService.DeleteNoteRequest request) {
            return base.Channel.DeleteNoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Notes.NoteService.DeleteNoteResponse> DeleteNoteAsync(string id) {
            Notes.NoteService.DeleteNoteRequest inValue = new Notes.NoteService.DeleteNoteRequest();
            inValue.Body = new Notes.NoteService.DeleteNoteRequestBody();
            inValue.Body.id = id;
            return ((Notes.NoteService.NoteControllerSoap)(this)).DeleteNoteAsync(inValue);
        }
    }
}
